version: '3'

services:
  postgres:
    restart: always
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PUBLISH_PORT}:5432'
  redis:
    restart: always
    image: 'redis:3.2-alpine'
    volumes:
      - './data/redis:/data'
    ports:
      - '${REDIS_PUBLISH_PORT}:6379'
  api:
    restart: always
    build: .
    ports:
      - '${PORT}:5000'
    command: ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "wsgi:application"]
    depends_on:
      - postgres
      - redis