version: '3'

services:
  postgres:
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - './data/postgres:/var/lib/postgresql/data'
    ports:
      - '${POSTGRES_PUBLISH_PORT}:5432'
  redis:
    image: 'redis:3.2-alpine'
    volumes:
      - './data/redis:/data'
    ports:
      - '${REDIS_PUBLISH_PORT}:6379'
  api:
    build: .
    ports:
      - '${PORT}:5000'
    command: ["./wait-for-it.sh", "python", "manage.py", "runserver", "-h", "0.0.0.0"]
    depends_on:
      - postgres
      - redis